### ISSUE TITLE
Definition of meta routes

### ISSUE THREAD

**Issue by popey456963** [joelparkerhenderson/social_network_plan#13]
In the document you include two references to meta-routing:

 - Could meta-routes make it easier to sign up?
 - Could meta-routes make it much easier to automate account creation?

Could you explain a little more about what meta-routes are?  The only reference I can find about it is including metadata in the routing algorithm, such as whether you need to be logged in to view a page or not.

**Comment by joelparkerhenderson** [comment]
Yes thanks for the question. I am adding this now. How do you react to this?

### Meta-routes

We use the term "routes" to generically describe ways to reach people, places, items, etc.

Examples:

* Email addresses use a route such as: alice@example.com
* Phones use an international standard such as: +1-415-317-2700
* Domains use a domain name route such as: reddit.com
* Facebook uses a URL username route such as http://facebook.com/alice
* Booksellers use a International Standard Book Number such as: 123456789

We use the term "meta-routes" to generically describe routes that contain other routes. 

Examples of URLs that are each a route that contains another route:

* Email address: https://www.example.com/alice@example.com
* Domain name: https://www.example.com/reddit.com
* Phone number: https://www.example.com/+1-415-317-2700
* Facebook user: https://www.example.com/facebook.com/alice
* Bookseller ISBN: https://www.example.com/isbn/123456789

Brainstorms:
* We speculate that meta-routes may make it easier, faster, and better, to create a user-friendly social network that also connects to other networks.
* For example meta-routes can automatically give each person their own page based on their email address, or on their multiple email addresses; the person doesn't have to choose a new username or compete with other people for usernames.
* For example, meta-routes may improve people's trust in the network, because the URL contains more information that can be automatically verified, such as verifying the person's email address by sending an email, or telephone number by sending a text message, or domain name by having a sysadmin add a DNS record.

**Comment by popey456963** [comment]
Oh I see, yes, I like that very much.  Makes it a lot clearer. :+1:

**Comment by joelparkerhenderson** [comment]
Good, then I'll close this issue now.
